FROM python:3.9-slim-buster

# Setup env
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
# timezone env with default
ENV TZ America/Sao_Paulo
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONFAULTHANDLER 1

WORKDIR /app/
ENV PYTHONPATH=/app

#instal container dependences
RUN apt-get update -yy \
    && apt-get upgrade -yy \
    && apt-get install -yy libpq-dev \
    && pip install --upgrade pip \
    && pip install --no-cache-dir pipenv

# Install python dependencies in /.venv
COPY Pipfile Pipfile.lock* /app/

# Allow installing dev dependencies to run tests
ARG INSTALL_DEV=true
RUN bash -c "if [ $INSTALL_DEV == 'true' ] ; then pipenv install --dev ; else pipenv install; fi"

COPY . .

CMD ["pipenv", "run", "manage.py", "runserver"]