name: CI Stage

on:
  pull_request:
    branches: [dev, main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create env file
        run: make config-env
  
      - name: Build Server
        run: make build

      - name: Run Service
        run: docker-compose up -d

      - name: Run Pylint
        run: make pylint

      - name: Run Flake8
        run: make flake8

      - name: Run tests and coverage
        run: make tests-cov